# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ncbi_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(554, 332)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_search = QtWidgets.QWidget(self.centralwidget)
        self.widget_search.setObjectName("widget_search")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_search)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_org = QtWidgets.QHBoxLayout()
        self.layout_org.setObjectName("layout_org")
        self.label_org = QtWidgets.QLabel(self.widget_search)
        self.label_org.setMaximumSize(QtCore.QSize(71, 16777215))
        self.label_org.setObjectName("label_org")
        self.layout_org.addWidget(self.label_org)
        self.edit_org = QtWidgets.QLineEdit(self.widget_search)
        self.edit_org.setObjectName("edit_org")
        self.layout_org.addWidget(self.edit_org)
        self.verticalLayout.addLayout(self.layout_org)
        self.layout_prod = QtWidgets.QHBoxLayout()
        self.layout_prod.setObjectName("layout_prod")
        self.label_prod = QtWidgets.QLabel(self.widget_search)
        self.label_prod.setMaximumSize(QtCore.QSize(71, 16777215))
        self.label_prod.setObjectName("label_prod")
        self.layout_prod.addWidget(self.label_prod)
        self.edit_prod = QtWidgets.QLineEdit(self.widget_search)
        self.edit_prod.setObjectName("edit_prod")
        self.layout_prod.addWidget(self.edit_prod)
        self.verticalLayout.addLayout(self.layout_prod)
        self.layout_key = QtWidgets.QHBoxLayout()
        self.layout_key.setObjectName("layout_key")
        self.label_key = QtWidgets.QLabel(self.widget_search)
        self.label_key.setMaximumSize(QtCore.QSize(71, 16777215))
        self.label_key.setObjectName("label_key")
        self.layout_key.addWidget(self.label_key)
        self.edit_key = QtWidgets.QLineEdit(self.widget_search)
        self.edit_key.setText("")
        self.edit_key.setObjectName("edit_key")
        self.layout_key.addWidget(self.edit_key)
        self.verticalLayout.addLayout(self.layout_key)
        self.button_write = QtWidgets.QPushButton(self.widget_search)
        self.button_write.setObjectName("button_write")
        self.verticalLayout.addWidget(self.button_write)
        self.verticalLayout_3.addWidget(self.widget_search)
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.widget_request = QtWidgets.QWidget(self.centralwidget)
        self.widget_request.setObjectName("widget_request")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_request)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_request = QtWidgets.QHBoxLayout()
        self.layout_request.setObjectName("layout_request")
        self.label_request = QtWidgets.QLabel(self.widget_request)
        self.label_request.setMaximumSize(QtCore.QSize(71, 16777215))
        self.label_request.setObjectName("label_request")
        self.layout_request.addWidget(self.label_request)
        self.edit_request = QtWidgets.QLineEdit(self.widget_request)
        self.edit_request.setEnabled(False)
        self.edit_request.setText("")
        self.edit_request.setObjectName("edit_request")
        self.layout_request.addWidget(self.edit_request)
        self.verticalLayout_2.addLayout(self.layout_request)
        self.button_go = QtWidgets.QPushButton(self.widget_request)
        self.button_go.setEnabled(False)
        self.button_go.setObjectName("button_go")
        self.verticalLayout_2.addWidget(self.button_go)
        self.verticalLayout_3.addWidget(self.widget_request)
        spacerItem1 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.label_messages = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_messages.setFont(font)
        self.label_messages.setText("")
        self.label_messages.setObjectName("label_messages")
        self.verticalLayout_3.addWidget(self.label_messages)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.button_write.clicked.connect(MainWindow.button_write_clicked)
        self.button_go.clicked.connect(MainWindow.button_go_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_org.setText(_translate("MainWindow", "Organisme"))
        self.label_prod.setText(_translate("MainWindow", "Produit"))
        self.label_key.setText(_translate("MainWindow", "Mot-clés"))
        self.button_write.setText(_translate("MainWindow", "Ecrire la requête"))
        self.label_request.setText(_translate("MainWindow", "Requete"))
        self.button_go.setText(_translate("MainWindow", "Go"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
