# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(585, 470)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.label_organism = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_organism.setFont(font)
        self.label_organism.setObjectName("label_organism")
        self.gridLayout.addWidget(self.label_organism, 0, 0, 1, 1)
        self.edit_organism = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_organism.setFont(font)
        self.edit_organism.setObjectName("edit_organism")
        self.gridLayout.addWidget(self.edit_organism, 0, 1, 1, 1)
        self.label_type = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_type.setFont(font)
        self.label_type.setObjectName("label_type")
        self.gridLayout.addWidget(self.label_type, 1, 0, 1, 1)
        self.box_type = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.box_type.setFont(font)
        self.box_type.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.box_type.setObjectName("box_type")
        self.box_type.addItem("")
        self.gridLayout.addWidget(self.box_type, 1, 1, 1, 1)
        self.button_request = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_request.setFont(font)
        self.button_request.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.button_request.setAutoDefault(True)
        self.button_request.setDefault(True)
        self.button_request.setFlat(False)
        self.button_request.setObjectName("button_request")
        self.gridLayout.addWidget(self.button_request, 1, 2, 1, 1)
        self.label_request = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_request.setFont(font)
        self.label_request.setObjectName("label_request")
        self.gridLayout.addWidget(self.label_request, 2, 0, 1, 1)
        self.edit_request = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_request.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_request.setFont(font)
        self.edit_request.setObjectName("edit_request")
        self.gridLayout.addWidget(self.edit_request, 2, 1, 1, 1)
        self.button_ok = QtWidgets.QPushButton(self.centralwidget)
        self.button_ok.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_ok.setFont(font)
        self.button_ok.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.button_ok.setObjectName("button_ok")
        self.gridLayout.addWidget(self.button_ok, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.layout_labels = QtWidgets.QVBoxLayout()
        self.layout_labels.setObjectName("layout_labels")
        self.label_create = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_create.setFont(font)
        self.label_create.setText("")
        self.label_create.setObjectName("label_create")
        self.layout_labels.addWidget(self.label_create)
        self.label_error = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_error.setFont(font)
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.layout_labels.addWidget(self.label_error)
        self.label_nb_result = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_nb_result.setFont(font)
        self.label_nb_result.setText("")
        self.label_nb_result.setObjectName("label_nb_result")
        self.layout_labels.addWidget(self.label_nb_result)
        self.verticalLayout.addLayout(self.layout_labels)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.box_type.setCurrentIndex(0)
        self.button_ok.clicked.connect(MainWindow.button_ok_clicked)
        self.button_ok.pressed.connect(MainWindow.button_ok_pressed)
        self.button_request.clicked.connect(MainWindow.button_request_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_organism.setText(_translate("MainWindow", "Organism"))
        self.label_type.setText(_translate("MainWindow", "Type"))
        self.box_type.setItemText(0, _translate("MainWindow", "Choisir..."))
        self.button_request.setText(_translate("MainWindow", "Ecrire la requête"))
        self.label_request.setText(_translate("MainWindow", "Request"))
        self.button_ok.setText(_translate("MainWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
